-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 21:49:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema starview
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starview
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starview` DEFAULT CHARACTER SET latin1 ;
USE `starview` ;

-- -----------------------------------------------------
-- Table `starview`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `street` TEXT NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `other_address_details` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`attribute` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`room` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`attribute_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`attribute_room` (
  `room_id` INT(11) NOT NULL,
  `attribute_id` INT(11) NOT NULL,
  PRIMARY KEY (`room_id`, `attribute_id`),
  INDEX `attribute_room_room_id_idx` (`room_id` ASC),
  INDEX `attribute_room_room_attribute_id_fk` (`attribute_id` ASC),
  CONSTRAINT `attribute_room_room_attribute_id_fk`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `starview`.`attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attribute_room_room_id_fk`
    FOREIGN KEY (`room_id`)
    REFERENCES `starview`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`company_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`company_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `forename` VARCHAR(50) NULL DEFAULT NULL,
  `surname` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(254) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `contact_person_id` INT(11) NULL DEFAULT NULL,
  `company_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `company_name_uniq` (`name` ASC),
  INDEX `contact_person_id_idx` (`contact_person_id` ASC),
  INDEX `company_company_type_id_idx` (`company_type_id` ASC),
  CONSTRAINT `company_company_type_id_fk`
    FOREIGN KEY (`company_type_id`)
    REFERENCES `starview`.`company_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_person_id_fk`
    FOREIGN KEY (`contact_person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`inquiry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`inquiry` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(45) NOT NULL,
  `to` VARCHAR(45) NOT NULL,
  `num_persons` INT(10) UNSIGNED NOT NULL,
  `person_id` INT(11) NOT NULL,
  `issued` DATE NOT NULL,
  `cancelled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC),
  CONSTRAINT `inquiry_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`booking` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employing_company_id` INT(11) NULL DEFAULT NULL,
  `referring_company_id` INT(11) NULL DEFAULT NULL,
  `referring_person_id` INT(11) NULL DEFAULT NULL,
  `checkin` DATE NULL DEFAULT NULL,
  `checkout` DATE NULL DEFAULT NULL,
  `canceled` TINYINT(1) NULL DEFAULT '0',
  `referring_inquiry` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `booking_referring_company_id_idx` (`referring_company_id` ASC),
  INDEX `booking_employing_company_id_idx` (`employing_company_id` ASC),
  INDEX `booking_referring_person_id_idx` (`referring_person_id` ASC),
  INDEX `fk_inquiry` (`referring_inquiry` ASC),
  CONSTRAINT `booking_employing_company_id_fk`
    FOREIGN KEY (`employing_company_id`)
    REFERENCES `starview`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `booking_referring_company_id_fk`
    FOREIGN KEY (`referring_company_id`)
    REFERENCES `starview`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `booking_referring_person_id_fk`
    FOREIGN KEY (`referring_person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquiry`
    FOREIGN KEY (`referring_inquiry`)
    REFERENCES `starview`.`inquiry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`payment_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`payment_card` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `expirationdate` VARCHAR(7) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`booking_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`booking_person` (
  `person_id` INT(11) NOT NULL,
  `booking_id` INT(11) NOT NULL,
  `isResponsible` TINYINT(1) NULL DEFAULT '0',
  `payment_card_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`, `booking_id`),
  INDEX `booking_person_booking_id_idx` (`booking_id` ASC),
  INDEX `booking_person_person_id_idx` (`person_id` ASC),
  INDEX `booking_person_payment_card_id_idx` (`payment_card_id` ASC),
  CONSTRAINT `booking_person_booking_id_fk`
    FOREIGN KEY (`booking_id`)
    REFERENCES `starview`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `booking_person_payment_card_id_fk`
    FOREIGN KEY (`payment_card_id`)
    REFERENCES `starview`.`payment_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `booking_person_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`booking_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`booking_room` (
  `booking_id` INT(11) NOT NULL,
  `room_id` INT(11) NOT NULL,
  PRIMARY KEY (`booking_id`, `room_id`),
  INDEX `booking_room_room_id_idx` (`room_id` ASC),
  CONSTRAINT `booking_room_booking_id_fk`
    FOREIGN KEY (`booking_id`)
    REFERENCES `starview`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `booking_room_room_id_fk`
    FOREIGN KEY (`room_id`)
    REFERENCES `starview`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`company_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`company_address` (
  `address_id` INT(11) NOT NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`address_id`, `company_id`),
  INDEX `company_address_address_id_idx` (`address_id` ASC),
  INDEX `company_address_company_id_idx` (`company_id` ASC),
  CONSTRAINT `company_address_address_id_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `starview`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_address_company_id_fk`
    FOREIGN KEY (`company_id`)
    REFERENCES `starview`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`employee_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`employee_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `legacy_social_insurance_number` VARCHAR(11) NULL DEFAULT NULL,
  `social_insurance_number` VARCHAR(13) NOT NULL,
  `employee_type_id` INT(11) NOT NULL,
  `person_id` INT(11) NOT NULL,
  UNIQUE INDEX `employee_social_insurance_number_uniq` (`social_insurance_number` ASC),
  UNIQUE INDEX `employee_legacy_social_insurance_number_uniq` (`legacy_social_insurance_number` ASC),
  INDEX `employee_employee_type_id_idx` (`employee_type_id` ASC),
  INDEX `employee_person_id_idx` (`person_id` ASC),
  UNIQUE INDEX `person_id_UNIQUE` (`person_id` ASC),
  PRIMARY KEY (`id`, `person_id`),
  CONSTRAINT `employee_employee_type_id_fk`
    FOREIGN KEY (`employee_type_id`)
    REFERENCES `starview`.`employee_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`language` (
  `id` INT(11) NOT NULL,
  `language` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`person_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`person_address` (
  `address_id` INT(11) NOT NULL,
  `person_id` INT(11) NOT NULL,
  PRIMARY KEY (`address_id`, `person_id`),
  INDEX `person_address_address_id_idx` (`address_id` ASC),
  INDEX `person_address_person_id_idx` (`person_id` ASC),
  CONSTRAINT `person_address_address_id_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `starview`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_address_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`person_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`person_company` (
  `person_id` INT(11) NOT NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`person_id`, `company_id`),
  INDEX `person_company_company_id_idx` (`company_id` ASC),
  INDEX `person_company_people_id_idx` (`person_id` ASC),
  CONSTRAINT `person_company_company_id_fk`
    FOREIGN KEY (`company_id`)
    REFERENCES `starview`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_company_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`person_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`person_language` (
  `person_id` INT(11) NOT NULL,
  `language_id` INT(11) NOT NULL,
  `is_preferred` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`, `language_id`),
  INDEX `language_id_idx` (`language_id` ASC),
  CONSTRAINT `person_language_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `starview`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_language_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`phone_number_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`phone_number_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`phone_number` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone_number_type_id` INT(11) NOT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `phone_number_phone_number_type_id_idx` (`phone_number_type_id` ASC),
  CONSTRAINT `phone_number_phone_number_type_id_fk`
    FOREIGN KEY (`phone_number_type_id`)
    REFERENCES `starview`.`phone_number_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`person_phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`person_phone` (
  `person_id` INT(11) NOT NULL,
  `phone_number_id` INT(11) NOT NULL,
  PRIMARY KEY (`person_id`, `phone_number_id`),
  INDEX `person_phone_phone_number_id_idx` (`phone_number_id` ASC),
  CONSTRAINT `person_phone_person_id_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `starview`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_phone_phone_number_id_fk`
    FOREIGN KEY (`phone_number_id`)
    REFERENCES `starview`.`phone_number` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `starview`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starview`.`picture` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_id` INT(11) NOT NULL,
  `link_to_picture` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `picture_room_id_idx` (`room_id` ASC),
  CONSTRAINT `picture_room_id_fk`
    FOREIGN KEY (`room_id`)
    REFERENCES `starview`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
